pythonProject/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    path('authenticate/', include('authenticate.urls', namespace='authenticate')),  # new

    path('accounts/', include('accounts.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='posts/list-posts.html'), name='home'),  # new
]

pythonProject/myproject/posts/urls.py
# posts/urls.py

from django.conf.urls import url

from . import views
from .views import (
    ListPostView,
    CreatePostView,
    UpdatePostView,
)

app_name = 'posts'
urlpatterns = [
    url(r'^create-posts/$', CreatePostView.as_view(), name='create-post'),
    url(r'^list-posts/$', ListPostView.as_view(), name='list-posts'),
    url(r'^update-post/(?P<pk>[-\w]+)$', UpdatePostView.as_view(), name='update-post'),
    url(r'^delete-post/(?P<pk>[-\w]+)$', views.delete_post, name='delete-post'),

]

pythonProject/myproject/posts/models.py
from __future__ import unicode_literals

from django.db import models
from rest_framework.reverse import reverse


class Post(models.Model):
    name = models.CharField(max_length=224, null=False, blank=False)
    content = models.TextField(max_length=254, null=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.content

    @staticmethod
    def get_absolute_url():
        return reverse('posts:list-posts', kwargs={})

pythonProject/myproject/posts/forms.py
# posts/forms.py

from django import forms

from .models import Post


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'content', ]

pythonProject/myproject/posts/views.py
# posts/views.py

from __future__ import unicode_literals

from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from .forms import CreatePostForm
from .models import Post


class ListPostView(ListView):
    model = Post

    def get(self, request, *args, **kwargs):
        template_name = 'posts/list-posts.html'  # sẽ được tạo ở phần dưới
        obj = {
            'posts': Post.objects.all()
        }
        return render(request, template_name, obj)


class CreatePostView(SuccessMessageMixin, CreateView):
    template_name = 'posts/create-post.html'
    form_class = CreatePostForm
    success_message = 'Crate Post successfully!'


class UpdatePostView(SuccessMessageMixin, UpdateView):
    template_name = 'posts/edit-post.html'
    model = Post
    fields = ['name', 'content', ]
    success_message = 'Update Post successfully!'

    def get_success_url(self):
        return reverse('posts:list-posts', kwargs={})


def delete_post(request, pk):
    post = Post.objects.filter(id=pk)
    post.delete()
    context = {
        "messages": "Delete Post successfully",
        'posts': Post.objects.all()
    }
    return render(request, 'posts/list-posts.html', context)

pythonProject/myproject/templates/posts/create-post.html
<!-- posts/templates/posts/create-post.html -->

{% extends "layouts/layout.html" %}
{% block title %}
Create Post | {{ block.super }}
{% endblock title %}
{% block content %}
<h4><small>Create Posts</small></h4>
<hr>
<div class="card-body">
    <div class="table-responsive">
        <form action="{% url 'posts:create-post' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="comment">Name<span style="color: red">*</span> :</label>
                <input class="form-control" name="name" required rows="5" type="text">
            </div>
            <div class="form-group">
                <label for="comment">Content<span style="color: red">*</span> :</label>
                <textarea class="form-control" name="content" required rows="5"></textarea>
            </div>
            <button class="btn btn-secondary" type="submit">Create Post</button>
        </form>
    </div>
</div>
{% endblock content %}

pythonProject/myproject/templates/posts/edit-post.html
<!-- posts/templates/posts/edit-post.html -->

{% extends "layouts/layout.html" %}
{% block title %}
Edit Post | {{ block.super }}
{% endblock title %}
{% block content %}
<h4><small>Edit Posts</small></h4>
<hr>
<div class="card-body">
    <div class="table-responsive">
        <form action="{% url 'posts:update-post' object.id %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="comment">Name<span style="color: red">*</span> :</label>
                <input class="form-control" name="name" required rows="5" type="text" value="{{object.name}}">
            </div>
            <div class="form-group">
                <label for="comment">Content<span style="color: red">*</span> :</label>
                <textarea class="form-control" name="content" required rows="5">{{object.content}}</textarea>
            </div>
            <button class="btn btn-secondary" type="submit">Update Post</button>
        </form>
    </div>
</div>
{% endblock content %}

pythonProject/myproject/templates/posts/list-posts.html
<!-- posts/templates/posts/list-posts.html -->

{% extends "layouts/layout.html" %}
{% block title %}
List Post | {{ block.super }}

{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!

<p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{% endif %}

<h4><small>List Posts</small></h4>
<hr>
{% if posts %}
{% for post in posts %}
<h2>{{post.name}}</h2>
<h5><span class="glyphicon glyphicon-time"></span> Post at {{post.timestamp}}</h5>
<p>{{post.content}}</p>
<a href="{% url 'posts:update-post' post.id %}">Edit</a>
<a href="{% url 'posts:delete-post' post.id %}" onclick="return confirm('Are you sure you want to delete this post?');">Delete</a>

<br><br>
{% endfor %}
{% else %}
No song.
{% endif %}
{% endblock content %}