pythonProject/myproject/accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

pythonProject/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    path('authenticate/', include('authenticate.urls', namespace='authenticate')),  # new

    path('accounts/', include('accounts.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='posts/list-posts.html'), name='home'),  # new
]

pythonProject/myproject/posts/urls.py
# posts/urls.py

from django.conf.urls import url

from . import views
from .views import (
    ListPostView,
    CreatePostView,
    UpdatePostView,
)

app_name = 'posts'
urlpatterns = [
    url(r'^create-posts/$', CreatePostView.as_view(), name='create-post'),
    url(r'^list-posts/$', ListPostView.as_view(), name='list-posts'),
    url(r'^update-post/(?P<pk>[-\w]+)$', UpdatePostView.as_view(), name='update-post'),
    url(r'^delete-post/(?P<pk>[-\w]+)$', views.delete_post, name='delete-post'),

]

pythonProject/myproject/templates/layouts/layout.html
<!-- posts/templates/layouts/layout.html -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}CRUD{% endblock title %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <style>
          footer {
            background-color: #555;
            color: white;
            padding: 15px;
          }
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row content">
              <div class="col-sm-3 sidenav">
                <h4>CRUD</h4>
                <ul class="nav nav-pills nav-stacked">
                  <li {% if request.path == "/posts/list-posts/" %}class="active"{% endif %}>
                    <a href= "{% url 'posts:list-posts' %}">List Posts</a>
                  </li>
                  <li {% if request.path == "/posts/create-posts/" %}class="active"{% endif %}>
                    <a href= "{% url 'posts:create-post' %}">create Posts</a>
                  </li>
                  <li {% if request.path == "/registration/signup/" %}class="active"{% endif %}>
                    <a href= "{% url 'accounts:signup' %}">signup</a>
                  </li>
                </ul><br>
              </div>
              <div class="col-sm-9">
                  {% block content %}
                  {% endblock content %}
              </div>
            </div>
          </div>
          <footer class="container-fluid">
            <p>My Project CRUD Posts</p>
          </footer>
    </body>
</html>